### ISSUE TITLE
Fix PropTypes validation warnings

### ISSUE THREAD

**Issue by zsherman** [dstuecken/react-settings-pane#3]
Currently seeing this in the new version of React:

```
warning.js?ccd8:36Warning: You are manually calling a React.PropTypes validation function for the `onMenuItemClick` prop on `SettingsContent`
```

**Comment by dstuecken** [comment]
I don't get this on React 15.3.1, can you tell me what exactly this warning causes?

**Comment by zsherman** [comment]
Scratch that, was getting it on < 15.3 – upgraded and all good now!
